/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcialn1;

import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author dbpan
 */
public class frmProblema4 extends javax.swing.JFrame {

    /**
     * Creates new form frmProblema4
     */
    public frmProblema4() {
        initComponents();
        sldOrden.addChangeListener((ChangeEvent evt) -> {
            int hours = sldOrden.getValue();
            lblHoras.setText(String.valueOf(hours));
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupSO = new javax.swing.ButtonGroup();
        rdbWindows = new javax.swing.JRadioButton();
        rdbLinux = new javax.swing.JRadioButton();
        rdbMac = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblSIstema = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        chkProgram = new javax.swing.JCheckBox();
        chkDgrafico = new javax.swing.JCheckBox();
        chkAdministracion = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        sldOrden = new javax.swing.JSlider();
        lblHoras = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btngroupSO.add(rdbWindows);
        rdbWindows.setText("Windows");
        rdbWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbWindowsActionPerformed(evt);
            }
        });

        btngroupSO.add(rdbLinux);
        rdbLinux.setText("Linux");

        btngroupSO.add(rdbMac);
        rdbMac.setText("Mac");

        lblSIstema.setText("Elije un sistema operativo");

        lblEspecialidad.setText("Elije tu especialidad");

        chkProgram.setText("Programación");
        chkProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProgramActionPerformed(evt);
            }
        });

        chkDgrafico.setText("Diseño Gráfico");
        chkDgrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDgraficoActionPerformed(evt);
            }
        });

        chkAdministracion.setText("Administración");

        jLabel3.setText("Horas que dedicas en el ordenador");

        sldOrden.setMaximum(50);
        sldOrden.setValue(15);

        lblHoras.setToolTipText("");

        jLabel2.setText("Horas");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSIstema)
                            .addComponent(rdbMac)
                            .addComponent(rdbLinux)
                            .addComponent(rdbWindows)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEspecialidad)
                            .addComponent(chkProgram)
                            .addComponent(chkDgrafico)
                            .addComponent(chkAdministracion)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(sldOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(lblHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnGenerar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSIstema)
                .addGap(18, 18, 18)
                .addComponent(rdbWindows)
                .addGap(20, 20, 20)
                .addComponent(rdbLinux)
                .addGap(18, 18, 18)
                .addComponent(rdbMac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEspecialidad)
                .addGap(18, 18, 18)
                .addComponent(chkProgram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDgrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkAdministracion)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(sldOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbWindowsActionPerformed
        
    }//GEN-LAST:event_rdbWindowsActionPerformed

    private void chkProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProgramActionPerformed

    private void chkDgraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDgraficoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDgraficoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String sistema = "";
        String especialidad = "";
        if(rdbWindows.isSelected())
            sistema = rdbWindows.getText();
       if(rdbLinux.isSelected())
            sistema = rdbLinux.getText();
       if(rdbMac.isSelected())
            sistema = rdbMac.getText();
       //++++++++++++++//
       if(chkProgram.isSelected())
            especialidad =especialidad +" "+ chkProgram.getText();
       if(chkDgrafico.isSelected())
            especialidad =especialidad +" "+ chkDgrafico.getText();
       if(chkAdministracion.isSelected())
            especialidad = especialidad +" "+chkAdministracion.getText();
        String horas = lblHoras.getText(); 
        JOptionPane.showMessageDialog(rootPane, 
                "Tu sistema operativo preferido es "+sistema
               + "\ntus especialidades son "+especialidad 
                + "\n y el numero de horas dedicadas al ordenador son " + horas,"Muestra Datos",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProblema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProblema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProblema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProblema4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProblema4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGenerar;
    private javax.swing.ButtonGroup btngroupSO;
    private javax.swing.JCheckBox chkAdministracion;
    private javax.swing.JCheckBox chkDgrafico;
    private javax.swing.JCheckBox chkProgram;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblHoras;
    private javax.swing.JLabel lblSIstema;
    private javax.swing.JRadioButton rdbLinux;
    private javax.swing.JRadioButton rdbMac;
    private javax.swing.JRadioButton rdbWindows;
    private javax.swing.JSlider sldOrden;
    // End of variables declaration//GEN-END:variables
}
